In [1]:
import datetime
import pandas as pd

class LibraryBooks:
    total_books = 0

    def __init__(self, title, author, available_copies, number_days):
        self.title = title
        self.author = author
        self.copies = available_copies
        self.max_borrow_days = number_days
        self.borrow_days = None
        self.borrow_datetime = None
        self.borrowers = []


    def user_data(self):

        pass


    def category(self, category_name, available_books):
        categories = {
            "spiritual": available_books[0],
            "murder-mystry": available_books[1],
            "realistic": available_books[2]
        }
        if category_name in categories:
            book = categories[category_name]
            if book.copies > 0:
                return book
            else:
                print(f"No copies available for {book.title}")
                return None
        else:
            print("Invalid category")
            return None


    def datetimer(self):
        self.borrow_datetime = datetime.datetime.now()
        return self.borrow_datetime


    def days(self, user_name, book_title, max_days):
        try:
            days = int(
                input(
                    f"Enter number of days {user_name} wants to borrow '{book_title}' (max {max_days}): "
                )
            )
            if days > max_days or days <= 0:
                print(f"Invalid number of days. Setting to default: {max_days}")
                return max_days
            else:
                return days
        except ValueError:
            print("Invalid input. Please enter a number.")
            return max_days


    @classmethod
    def find_common_books(cls, df):
        """Finds books borrowed by more than one person using a DataFrame."""
        if df.empty:
            print("No books have been borrowed yet.")
            return {}

        borrow_counts = df.groupby("Title")["User Name"].nunique()
        common_books_titles = borrow_counts[borrow_counts > 1].index.tolist()

        if common_books_titles:
            print("\nCommon books borrowed by multiple users:")
            for title in common_books_titles:
                borrowers = df[df["Title"] == title]["User Name"].unique().tolist()
                print(f"- '{title}' borrowed by: {', '.join(borrowers)}")
        else:
            print("\nNo books have been borrowed by multiple users yet.")

        return common_books_titles

    @classmethod
    def show_books_by_user(cls, df, user_name):
        """Shows books borrowed by a specific user using a DataFrame."""
        user_books_df = df[df["User Name"] == user_name]

        if not user_books_df.empty:
            print(f"\nBooks borrowed by {user_name}:")
            for index, row in user_books_df.iterrows():
                print(f"- {row['Title']}")
        else:
            print(f"\n{user_name} has not borrowed any books yet.")


    @classmethod
    def total_book_borrow(cls, data_list):
        """Calculates the total number of books borrowed based on the list of borrowed data."""
        return len(data_list)


book1 = LibraryBooks(
    "Autobiograpy of yogi",
    "Paramahansa Yogananda",
    3,
    7,
)
book2 = LibraryBooks("sherlock holmes", "Arthur Conan", 2, 5)
book3 = LibraryBooks("Rich dad poor dad", "Robert Kiyosak", 4, 10)

all_data = []


books = [book1, book2, book3]


num_borrowers = 3

for i in range(num_borrowers):
    print(f"\n--- Borrower {i+1} ---")

    
    print("welcome to our library-system user ")
    print("please enter your following detail:")
    user_name = input(f"Enter name for borrower {i+1}: ")
    try:
        user_age = int(input(f"Enter age for borrower {i+1}: "))
    except ValueError:
        print("Invalid age. Please enter a number.")
        user_age = None
    user_gender = input(f"Enter gender for borrower {i+1}: ")
    user_address = input(f"Enter address for borrower {i+1}: ")
    mobile_input = input(f"Enter mobile number for borrower {i+1}: ")
    if len(mobile_input) > 10:
      print("Invalid number")
      user_mobile_number = None
    else:
      try:
          user_mobile_number = int(mobile_input)
      except ValueError:
          print("Invalid mobile number. Please enter a number.")
          user_mobile_number = None


    print("\nAvailable categories: spiritual, murder-mystry, realistic")
    chosen_category = input(f"Enter the category of book {user_name} wants to borrow (e.g., spiritual, murder-mystry, realistic): ")


    temp_library_instance = LibraryBooks("", "", 0, 0)
    borrowed_book = temp_library_instance.category(chosen_category, books)

    if borrowed_book:
        print(f"{user_name} borrowed {borrowed_book.title}")

        borrowed_book.borrowers.append(user_name)

        borrow_days = temp_library_instance.days(user_name, borrowed_book.title, borrowed_book.max_borrow_days)
        borrow_datetime = temp_library_instance.datetimer()


        all_data.append({
            "User Name": user_name,
            "User Age": user_age,
            "User Gender": user_gender,
            "User Address": user_address,
            "User Mobile": user_mobile_number,
            "Title": borrowed_book.title,
            "Author": borrowed_book.author,
            "Available Copies": borrowed_book.copies,
            "Borrow Days (max)": borrowed_book.max_borrow_days,
            "Borrowed Days": borrow_days,
            "Time of borrow": borrow_datetime
        })
    else:
        print(f"Could not find a book in the chosen category or invalid category for {user_name}.")


df = pd.DataFrame(all_data)
print("\n--- Borrowing Data ---")
display(df)
print(f"\nTotal books borrowed: {LibraryBooks.total_book_borrow(all_data)}")
print(f"\nTotal available books: {sum(book.copies for book in books)}")

common_books = LibraryBooks.find_common_books(df)

user_to_search = input("\nEnter the name of the user to see their borrowed books: ")
LibraryBooks.show_books_by_user(df, user_to_search)


--- Borrower 1 ---
welcome to our library-system user 
please enter your following detail:


Enter name for borrower 1:  hrishikesh
Enter age for borrower 1:  21
Enter gender for borrower 1:  male
Enter address for borrower 1:  malegaon
Enter mobile number for borrower 1:  9699346686



Available categories: spiritual, murder-mystry, realistic


Enter the category of book hrishikesh wants to borrow (e.g., spiritual, murder-mystry, realistic):  spiritual


hrishikesh borrowed Autobiograpy of yogi


Enter number of days hrishikesh wants to borrow 'Autobiograpy of yogi' (max 7):  7



--- Borrower 2 ---
welcome to our library-system user 
please enter your following detail:


Enter name for borrower 2:  neha
Enter age for borrower 2:  21
Enter gender for borrower 2:  female
Enter address for borrower 2:  pune
Enter mobile number for borrower 2:  8605639370



Available categories: spiritual, murder-mystry, realistic


Enter the category of book neha wants to borrow (e.g., spiritual, murder-mystry, realistic):  spirirtual


Invalid category
Could not find a book in the chosen category or invalid category for neha.

--- Borrower 3 ---
welcome to our library-system user 
please enter your following detail:


Enter name for borrower 3:  roy
Enter age for borrower 3:  24
Enter gender for borrower 3:  male
Enter address for borrower 3:  mumbai
Enter mobile number for borrower 3:  9518770670



Available categories: spiritual, murder-mystry, realistic


Enter the category of book roy wants to borrow (e.g., spiritual, murder-mystry, realistic):  spiritual


roy borrowed Autobiograpy of yogi


Enter number of days roy wants to borrow 'Autobiograpy of yogi' (max 7):  6



--- Borrowing Data ---


,User Name,User Age,User Gender,User Address,User Mobile,Title,Author,Available Copies,Borrow Days (max),Borrowed Days,Time of borrow
0,hrishikesh,21,male,malegaon,9699346686,Autobiograpy of yogi,Paramahansa Yogananda,3,7,7,2025-07-31 18:04:46.638651
1,roy,24,male,mumbai,9518770670,Autobiograpy of yogi,Paramahansa Yogananda,3,7,6,2025-07-31 18:06:20.798855



Total books borrowed: 2

Total available books: 9

Common books borrowed by multiple users:
- 'Autobiograpy of yogi' borrowed by: hrishikesh, roy



Enter the name of the user to see their borrowed books:  hrishikesh



Books borrowed by hrishikesh:
- Autobiograpy of yogi


In [25]:
copies=np.sum(df["Available Copies"])


IndexError: invalid index to scalar variable.

In [31]:
# df["Available Copies"]
df


6

In [5]:
import numpy as np

In [19]:
arr=np.random.randint(100,size=12)
print(arr.reshape(3,4))

[[35  8 25 28]
 [44 57 26  7]
 [53 71 20 97]]
